services:
  - type: web
    name: twig-stage2
    env: php
    rootDir: stage2/twig
    buildCommand: ""
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: RENDER_PHP_VERSION
        value: 8.2
